version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      react:
        applies-to: version-updates
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      react-security:
        applies-to: security-updates
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      codeql:
        applies-to: version-updates
        patterns:
          - 'github/codeql-action/*'
      codeql-security:
        applies-to: security-updates
        patterns:
          - 'github/codeql-action/*'
